version: "3.8"
services:
  backend:
    build: ./backend
    environment:
      - PORT=${PORT:-8080}
      - DB_FILE=${DB_FILE:-./budget.sqlite}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:5173}
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "5173:80"
    depends_on:
      - backend
